version: '3.9'

services:
    pedidos:
        build: .
        ports:
            - 5001:5000
        volumes:
            - .:/app
        environment:
            - FLASK_ENV=development
            - FLASK_APP=/app/src/main.py
            - PYTHONUNBUFFERED=1

    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        environment:
            - POSTGRES_PASSWORD=1234
        ports:
            - 5434:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
