"""empty message

Revision ID: cff6e971e556
Revises: e74f83141eb4
Create Date: 2021-06-25 13:16:27.672063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff6e971e556'
down_revision = 'e74f83141eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido', 'uuid')
    # ### end Alembic commands ###
